*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVCONF_DIR......................................*
FORM GET_DATA_ZVCONF_DIR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCONF_DIR WHERE
(VIM_WHERETAB) .
    CLEAR ZVCONF_DIR .
ZVCONF_DIR-MANDT =
ZCONF_DIR-MANDT .
ZVCONF_DIR-ZMODULE =
ZCONF_DIR-ZMODULE .
ZVCONF_DIR-DIR_NO =
ZCONF_DIR-DIR_NO .
ZVCONF_DIR-DIR_TEXT =
ZCONF_DIR-DIR_TEXT .
<VIM_TOTAL_STRUC> = ZVCONF_DIR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVCONF_DIR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVCONF_DIR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVCONF_DIR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCONF_DIR WHERE
  ZMODULE = ZVCONF_DIR-ZMODULE AND
  DIR_NO = ZVCONF_DIR-DIR_NO .
    IF SY-SUBRC = 0.
    DELETE ZCONF_DIR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCONF_DIR WHERE
  ZMODULE = ZVCONF_DIR-ZMODULE AND
  DIR_NO = ZVCONF_DIR-DIR_NO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCONF_DIR.
    ENDIF.
ZCONF_DIR-MANDT =
ZVCONF_DIR-MANDT .
ZCONF_DIR-ZMODULE =
ZVCONF_DIR-ZMODULE .
ZCONF_DIR-DIR_NO =
ZVCONF_DIR-DIR_NO .
ZCONF_DIR-DIR_TEXT =
ZVCONF_DIR-DIR_TEXT .
    IF SY-SUBRC = 0.
    UPDATE ZCONF_DIR ##WARN_OK.
    ELSE.
    INSERT ZCONF_DIR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVCONF_DIR-UPD_FLAG,
STATUS_ZVCONF_DIR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVCONF_DIR.
  SELECT SINGLE * FROM ZCONF_DIR WHERE
ZMODULE = ZVCONF_DIR-ZMODULE AND
DIR_NO = ZVCONF_DIR-DIR_NO .
ZVCONF_DIR-MANDT =
ZCONF_DIR-MANDT .
ZVCONF_DIR-ZMODULE =
ZCONF_DIR-ZMODULE .
ZVCONF_DIR-DIR_NO =
ZCONF_DIR-DIR_NO .
ZVCONF_DIR-DIR_TEXT =
ZCONF_DIR-DIR_TEXT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVCONF_DIR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVCONF_DIR-ZMODULE TO
ZCONF_DIR-ZMODULE .
MOVE ZVCONF_DIR-DIR_NO TO
ZCONF_DIR-DIR_NO .
MOVE ZVCONF_DIR-MANDT TO
ZCONF_DIR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCONF_DIR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCONF_DIR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCONF_DIR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
